config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new_admin", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  delete "/coaches/sign_out" => "sessions#destroy_coach", as: "coaches_sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/coaches/sign_in" => "sessions#new_coach", as: "coaches_sign_in"
  get "/logged_in" => "sessions#logged_in", as: "logged_in"
  post "/session" => "sessions#create", as: "session"

  root to: "events#index"
  resources :coaches, except: [:show] do
    collection do
      get 'sign_up', to: 'coaches#new'
      get 'events', to: 'coaches/events#index'
    end
  end
  resources :events do
    resources :applications do
      get :confirm, to: "applications#confirm"
      get :cancel, to: "applications#cancel"
    end
    resources :coach_applications
  end

  namespace :admin do
    root to: "events#index"
    resources :users do
      member do
        put :blacklist
      end
    end
    resources :events do
      resources :applications do
        collection do
          put :update_statuses
        end
      end
      resources :groups, only: [:index] do
        collection do
          post :generate
          post :regenerate
        end
      end
      put :complete
      put :send_emails
      resources :templates
      resources :attendants
      resources :coach_applications do
        collection do
          put :update_statuses
          put :send_approval_emails
        end
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :applications
  has_many :coach_applications
  has_many :event_groups
  before_create :copy_templates

  validates :name, :place, :scheduled_at, :application_start, :application_end, :confirmation_date, :start_time, :end_time, presence: true
  validate :right_order_of_dates

  def self.send_reminders
    Event.where("scheduled_at - current_date = reminder_date").each do |event|
      event.applications.where(state: :application_selected, attendance_confirmed: true).each do |application|
        UserMailer.reminder_mail(application).deliver_now
      end
    end
    Event.where("scheduled_at = current_date + 1 + confirmation_deadline").each do |event|
      event.applications.where(state: :application_selected, attendance_confirmed: false).each do |application|
        UserMailer.reminder_attendance_mail(application).deliver_now
      end
    end
  end

  attr_accessor :copy_templates_from_event_id

  def name_and_date
    scheduled_at.to_s + " " + name
  end

  def has_groups?
    !event_groups.empty?
  end

private

  def right_order_of_dates
    dates = [application_start, application_end, confirmation_date, scheduled_at]
    if dates != dates.sort
      errors.add(:scheduled_at, "Dates aren't in the right order.")
    end
  end

  def copy_templates
    unless copy_templates_from_event_id.blank?
      event = Event.find(copy_templates_from_event_id)
      self.application_mail = event.application_mail
      self.selection_mail = event.selection_mail
      self.rejection_mail = event.rejection_mail
      self.waiting_list_mail = event.waiting_list_mail
      self.reminder_mail = event.reminder_mail
      self.application_mail_subject = event.application_mail_subject
      self.selection_mail_subject = event.selection_mail_subject
      self.rejection_mail_subject = event.rejection_mail_subject
      self.waiting_list_mail_subject = event.waiting_list_mail_subject
      self.reminder_mail_subject = event.reminder_mail_subject
      self.reminder_attendance_mail = event.reminder_attendance_mail
      self.reminder_attendance_mail_subject = event.reminder_attendance_mail_subject
      self.coach_approval_mail = event.coach_approval_mail
      self.coach_approval_mail_subject = event.coach_approval_mail_subject
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout "admin"

  before_action :require_admin
  before_action :find_event, only: [:edit, :update, :destroy, :complete, :send_emails]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    render :edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to edit_admin_event_path(@event)
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to admin_events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path
  end

  def complete
    @event.update_attributes(selection_complete: true)
    send_selection_emails @event.applications.application_selected
    send_rejection_emails @event.applications.rejected
    send_waiting_list_emails @event.applications.waiting_list

    redirect_to admin_event_applications_path(@event)
  end

  def send_emails
    send_selection_emails @event.applications.application_selected.not_marked_as_selected
    redirect_to admin_event_applications_path(@event)
  end

private

  def find_event
    @event = Event.find(params[:id] || params[:event_id])
  end

  def event_params
    params.require(:event).
      permit(:name,
        :place,
        :scheduled_at,
        :application_start,
        :application_end,
        :confirmation_date,
        :start_time,
        :end_time,
        :copy_templates_from_event_id,
        :confirmation_deadline,
        :reminder_date,
        :coach_registration_enabled,
        :coach_the_coaches_date,
        :coach_the_coaches_start_time,
        :coach_the_coaches_end_time,
        :installation_get_together_date,
        :installation_get_together_start_time,
        :installation_get_together_end_time)
  end

  def send_selection_emails(applications)
    applications.each do |application|
      UserMailer.selection_mail(application).deliver_later
      application.update_attributes(selected_on: Date.today)
    end
  end

  def send_rejection_emails(applications)
    applications.each do |application|
      UserMailer.rejection_mail(application).deliver_later
    end
  end

  def send_waiting_list_emails(applications)
    applications.each do |application|
      UserMailer.waiting_list_mail(application).deliver_later
    end
  end
end

app/controllers/coaches/events_controller.rb
class Coaches::EventsController < CoachesController
  def index
    @events = Event.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_if_coach, only: [:index]

  def index
    @events = Event.all.sort_by &:scheduled_at
  end

  private

  def check_if_coach
    if current_user && current_user.coach
      redirect_to events_coaches_path
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper

  def link_to_active(text, url)
    link_to(text, url, class: ("active" if current_page?(url)))
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event_menu.html.erb
<nav class="email-templates-menu">
  <ul>
    <li><%= link_to_active "General info", edit_admin_event_path(@event) %></li>
    <li><%= link_to_active "Application e-mail", edit_admin_event_template_path(@event, :application_mail) %></li>
    <li><%= link_to_active "Selection e-mail", edit_admin_event_template_path(@event, :selection_mail) %></li>
    <li><%= link_to_active "Waiting list e-mail", edit_admin_event_template_path(@event, :waiting_list_mail) %></li>
    <li><%= link_to_active "Rejection e-mail", edit_admin_event_template_path(@event, :rejection_mail) %></li>
    <li><%= link_to_active "Reminder e-mail", edit_admin_event_template_path(@event, :reminder_mail) %></li>
    <li><%= link_to_active "Confirmation reminder e-mail", edit_admin_event_template_path(@event, :reminder_attendance_mail) %></li>
    <li><%= link_to_active "Coach approval e-mail", edit_admin_event_template_path(@event, :coach_approval_mail) %></li>
  </ul>
</nav>

app/views/admin/events/edit.html.erb
<%= render partial: "event_menu" if  @event.persisted? %>

<%= form_for [:admin, @event] do |f| %>
<fieldset class="form-border">
  <legend class="form-title">Workshop</legend>
  <p><%= f.label(:name, "Name") %></p>
  <%= error_message(@event, :name) %>
  <p><%= f.text_field :name %></p>

  <p><%= f.label(:place, "Place") %></p>
  <%= error_message(@event, :place) %>
  <p><%= f.text_field :place %></p>

  <p><%= f.label(:scheduled_at, "Workshop date") %></p>
  <%= error_message(@event, :scheduled_at) %>
  <p><%= f.date_select :scheduled_at %></p>

  <p><%= f.label(:start_time, "Workshop starts at:") %></p>
  <%= error_message(@event, :start_time) %>
  <p><%= f.time_select :start_time %></p>

  <p><%= f.label(:end_time, "Workshop ends at:") %></p>
  <%= error_message(@event, :end_time) %>
  <p><%= f.time_select :end_time %></p>
</fieldset>
<fieldset class="form-border">
  <legend class="form-title">Coach the Coaches</legend>
  <p><%= f.label(:coach_the_coaches_date, "Coach the Coaches date:") %></p>
  <%= error_message(@event, :coach_the_coaches_date) %>
  <p><%= f.date_select :coach_the_coaches_date %></p>

  <p><%= f.label(:coach_the_coaches_start_time, "Coach the coaches starts at:") %></p>
  <%= error_message(@event, :coach_the_coaches_start_time) %>
  <p><%= f.time_select :coach_the_coaches_start_time %></p>

  <p><%= f.label(:coach_the_coaches_end_time, "Coach the coaches ends at:") %></p>
  <%= error_message(@event, :coach_the_coaches_end_time) %>
  <p><%= f.time_select :coach_the_coaches_end_time %></p>
</fieldset>
<fieldset class="form-border">
  <legend class="form-title">Installation Get-Together</legend>
  <p><%= f.label(:installation_get_together_date, "Installation Get-Together date:") %></p>
  <%= error_message(@event, :installation_get_together_date) %>
  <p><%= f.date_select :installation_get_together_date %></p>

  <p><%= f.label(:installation_get_together_start_time, "Installation Get-Together starts at:") %></p>
  <%= error_message(@event, :installation_get_together_start_time) %>
  <p><%= f.time_select :installation_get_together_start_time %></p>

  <p><%= f.label(:installation_get_together_end_time, "Installation Get-Together ends at:") %></p>
  <%= error_message(@event, :installation_get_together_end_time) %>
  <p><%= f.time_select :installation_get_together_end_time %></p>
</fieldset>
<fieldset class="form-border">
  <legend class="form-title">Registrations</legend>
  <p><%= f.label(:application_start, "Applications start on:") %></p>
  <%= error_message(@event, :application_start) %>
  <p><%= f.date_select :application_start %></p>

  <p><%= f.label(:application_end, "Applications end on:") %></p>
  <%= error_message(@event, :application_end) %>
  <p><%= f.date_select :application_end %></p>

  <p><%= f.label(:confirmation_date, "Confirmation emails sent by:") %></p>
  <%= error_message(@event, :confirmation_date) %>
  <p><%= f.date_select :confirmation_date %></p>

	<p><%= f.label(:confirmation_deadline, "Days to confirm participation:") %></p>
	<%= error_message(@event, :confirmation_deadline) %>
	<p><%= f.number_field :confirmation_deadline %></p>

	<p><%= f.label(:reminder_date, "Days to send the reminder email:") %></p>
	<%= error_message(@event, :reminder_date) %>
	<p><%= f.number_field :reminder_date %></p>

  <p><%= f.label(:coach_registration_enabled, "Coach registration enabled?") %> <%= f.check_box :coach_registration_enabled %></p>
	<%= error_message(@event, :coach_registration_enabled) %>

  <% unless @event.persisted? %>
  <p><%= f.label(:copy_templates_from_event_id, "Use email templates from event:") %></p>
  <%= error_message(@event, :copy_templates_from_event_id) %>
  <p><%= f.collection_select(:copy_templates_from_event_id, Event.order(:scheduled_at), :id, :name_and_date, prompt: "Leave templates empty") %></p>
  <% end %>
</fieldset>

<br>
<div class='button'>
  <%= f.submit "Save", class: 'commit', type: 'submit' %>
</div>
<% end %>

app/views/admin/events/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
    <tr>
      <td>
        <%= event.name %>
      </td>
      <td>
        <%= l event.scheduled_at %>
      </td>
      <td class="actions">
        <%= link_to 'Applicants', admin_event_applications_path(event) %>
        <%= link_to 'Attendees', admin_event_attendants_path(event) %>
        <%= link_to 'Coaches', admin_event_coach_applications_path(event) %>
        <%= link_to 'Groups', admin_event_groups_path(event) %>
        <%= link_to 'Edit', edit_admin_event_path(event) %>
        <%= button_to 'Delete', admin_event_path(event), method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
  </tr>
    <%end %>
  </tbody>
</table>

<p><%= button_to 'Add event', new_admin_event_path, method: :get  %></p>