config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new_admin", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  delete "/coaches/sign_out" => "sessions#destroy_coach", as: "coaches_sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/coaches/sign_in" => "sessions#new_coach", as: "coaches_sign_in"
  get "/logged_in" => "sessions#logged_in", as: "logged_in"
  post "/session" => "sessions#create", as: "session"

  root to: "events#index"
  resources :coaches, except: [:show] do
    collection do
      get 'sign_up', to: 'coaches#new'
      get 'events', to: 'coaches/events#index'
    end
  end
  resources :events do
    resources :applications do
      get :confirm, to: "applications#confirm"
      get :cancel, to: "applications#cancel"
    end
    resources :coach_applications
  end

  namespace :admin do
    root to: "events#index"
    resources :users do
      member do
        put :blacklist
      end
    end
    resources :events do
      resources :applications do
        collection do
          put :update_statuses
        end
      end
      resources :groups, only: [:index] do
        collection do
          post :generate
          post :regenerate
        end
      end
      put :complete
      put :send_emails
      resources :templates
      resources :attendants
      resources :coach_applications do
        collection do
          put :update_statuses
          put :send_approval_emails
        end
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coach_application.rb
class CoachApplication < ApplicationRecord
  belongs_to :coach
  belongs_to :event
  accepts_nested_attributes_for :coach
  accepts_nested_attributes_for :event

  scope :to_contact, -> { where(contacted_at: nil, state: :approved) }
  scope :approved, ->{ where(state: :approved) }

  enum state: { pending: 0, approved: 1, rejected: 2, cancelled: 3 }

  def destroy
    update_attribute(:state, :cancelled)
  end
end

app/controllers/admin/coach_applications_controller.rb
class Admin::CoachApplicationsController < ApplicationsController
  layout "admin"

  before_action :require_admin
  before_action :find_event

  def index
    @coach_applications = @event.coach_applications.includes(coach: :user).
      order(params[:order] || "created_at desc")
  end

  def update_statuses
    approved_ids = params[:approved_ids] || [-1]
    # This code might cause performance problems. If application too slow, it needs refactoring.
    params[:state].each do |application_id, state|
      application = CoachApplication.find(application_id)
      application.state = state
      application.save!
    end

    @event.coach_applications.update_all(["lightningtalk_approved = (id IN (?))", approved_ids])

    redirect_to admin_event_coach_applications_path(@event), notice: "Cool! Changes saved."
  end

  def send_approval_emails
    @event.coach_applications.includes(coach: :user).to_contact.each do |coach_application|
      coach_application.update_attribute(:contacted_at, Time.now)
      UserMailer.coach_approval_mail(coach_application).deliver_later
    end

    redirect_to admin_event_coach_applications_path(@event), notice: "E-mails sent"
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/coach_applications_controller.rb
class CoachApplicationsController < ApplicationController
  layout "coach"
  before_action :find_event
  before_action :find_coach_application, only: :destroy
  before_action :require_coach
  before_action :check_application_status, only: [:new, :create]

  def new
    if @event.application_start > current_time
      flash[:error] = "Too early to apply"
      redirect_to events_coaches_path
    elsif @event.application_end < current_time
      render :too_late
    elsif !@event.coach_registration_enabled
      flash[:error] = "Registration not available"
      redirect_to events_coaches_path
    else
      @coach_application = CoachApplication.new
      @coach_application.coach = current_user.coach
      @coach_application.event = @event
    end
  end

  def create
    @coach_application = CoachApplication.new(create_coach_application_params)
    #make coach and event available for new view
    @coach_application.coach = current_user.coach
    @coach_application.event = @event

    if @coach_application.save
      render :successful_registration
    else
      render :new
    end
  end

  def destroy
    if @coach_application.destroy
      flash[:notice] = "Application cancelled"
    else
      flash[:error] = "Something went wrong"
    end

    redirect_to events_coaches_path
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_coach_application
    @coach_application = CoachApplication.find(params[:id])
  end

  def create_coach_application_params
    params.require(:coach_application).
      permit(:installationparty, :workshopday, :lightningtalk, :notes, :first_time_coaching, :coach_the_coaches, :sponsor)
  end

  def check_application_status
    if @event.coach_applications.find_by(coach_id: current_user.coach.id)
      flash[:error] = "You already applied"
      redirect_back(fallback_location: events_coaches_path)
    end
  end
end

app/helpers/coach_applications_helper.rb
module CoachApplicationsHelper
  def coach_application_states_for_select
    CoachApplication.states.map do |key, _|
      [CoachApplication.human_attribute_name("state.#{key}"), key]
    end
    end
end

app/views/admin/coach_applications/index.html.erb
<p>Total: <%= pluralize(@coach_applications.size, "application") %> </p>

<%= form_tag({ action: :update_statuses }, method: :put) do %>
<table>
  <thead>
    <tr>
      <th><%= link_to("No.", order: order("sequence_number"), class: "table-header-link") %></th>
      <th><%= link_to("Status", order: order("state"), class: "table-header-link") %></th>
      <th><%= link_to("Name", order: order("upper(name)"), class: "table-header-link") %></th>
      <th><%= link_to("Email", order: order("upper(email)"), class: "table-header-link") %></th>
      <th><div class="tooltip"><span class="tooltiptext">English</span><%= link_to("🇬🇧", order: order("language_en")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">German</span><%= link_to("🇩🇪", order: order("language_de")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">Gender</span>Gender</div></th>
      <th><div class="tooltip"><span class="tooltiptext">Installation party</span>🖥</div></th>
      <th><div class="tooltip"><span class="tooltiptext">Workshop day</span>🎓</div></th>
      <th><div class="tooltip"><span class="tooltiptext">Lightning talk approved</span>🆗</div></th>
      <th><div class="tooltip"><span class="tooltiptext">Lightning talk</span>🗣</div></th>
      <th><%= link_to("Date", order: order("created_at"), class: "table-header-link") %></th>
      <th><%= link_to("Comments", order: order("notes"), class: "table-header-link") %></th>
    </tr>
  </thead>
  <tbody>
    <% @coach_applications.each do |application| %>
    <tr>
      <td><%= application.id %>.</td>
      <td class="<%= application.state %>"><%= select_tag "state[#{application.id}]", options_for_select(coach_application_states_for_select, application.state) %></td>
      <td><%= application.coach.name %></td>
      <td><%= application.coach.user.email %></td>
      <td class="center"><% if application.coach.language_en %> ✅ <% end %></td>
      <td class="center"><% if application.coach.language_de %> ✅ <% end %></td>
      <td class="center"><%= application.coach.gender.humanize %></td>
      <td class="center"><% if application.installationparty %> ✅ <% end %></td>
      <td class="center"><% if application.workshopday %> ✅ <% end %></td>
      <td>
        <% unless application.lightningtalk.blank? %>
          <div style="text-align:center"><%= check_box_tag 'approved_ids[]', application.id, application.lightningtalk_approved, id: "lightningtalk_approved_#{application.id}" %></div>
        <% end %>
      </td>
      <td class="center"><%= application.lightningtalk %></td>
      <td><%= l application.created_at, format: :date %></td>
      <td class="shorten-long-text"><%= application.notes %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p><%= submit_tag "Save" %></p>
<% end %>

<% unless @coach_applications.to_contact.empty? %>
  <%= button_to "Send #{pluralize(@coach_applications.to_contact.size, 'e-mail')}", send_approval_emails_admin_event_coach_applications_path(@event), method: :put, data: { confirm: "Are you sure? This will send e-mails to the selected applicants." } %>
<% end %>