config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new_admin", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  delete "/coaches/sign_out" => "sessions#destroy_coach", as: "coaches_sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/coaches/sign_in" => "sessions#new_coach", as: "coaches_sign_in"
  get "/logged_in" => "sessions#logged_in", as: "logged_in"
  post "/session" => "sessions#create", as: "session"

  root to: "events#index"
  resources :coaches, except: [:show] do
    collection do
      get 'sign_up', to: 'coaches#new'
      get 'events', to: 'coaches/events#index'
    end
  end
  resources :events do
    resources :applications do
      get :confirm, to: "applications#confirm"
      get :cancel, to: "applications#cancel"
    end
    resources :coach_applications
  end

  namespace :admin do
    root to: "events#index"
    resources :users do
      member do
        put :blacklist
      end
    end
    resources :events do
      resources :applications do
        collection do
          put :update_statuses
        end
      end
      resources :groups, only: [:index] do
        collection do
          post :generate
          post :regenerate
        end
      end
      put :complete
      put :send_emails
      resources :templates
      resources :attendants
      resources :coach_applications do
        collection do
          put :update_statuses
          put :send_approval_emails
        end
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
require "csv"

class Application < ApplicationRecord
  validates :female, acceptance: { message: "You must identify as a woman or non-binary person to participate." }
  validates :name, presence: { message: "Please tell us your name." }
  validates :email, presence: { message: "Please enter your e-mail address." }
  validates :level, presence: { message: "Which level of coding do you have?" }
  validates :email, uniqueness: { scope: :event_id, message: "This e-mail address has already been used to apply for this workshop." }
  validates :email, email: { message: "This e-mail address is not valid." }
  validates :level, numericality: { message: "The level has to be a number from 0 to 10.", only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :os, presence: { message: "We need to know the operating system of your computer." }, unless: :needs_computer?
  validate :at_least_select_one_language
  validates :read_coc, acceptance: { message: "You must confirm that you have read the Code of Conduct and will comply with it." }
  validates :sequence_number, uniqueness: { scope: :event_id }, presence: true

  belongs_to :event

  scope :application_selected, -> { where(state: :application_selected) }
  scope :rejected, -> { where(state: :rejected) }
  scope :waiting_list, -> { where(state: :waiting_list) }
  scope :cancelled, -> { where(state: :cancelled) }
  scope :not_marked_as_selected, -> { where(selected_on: nil) }
  scope :confirmed, -> { where(attendance_confirmed: true) }
  scope :language_de, -> { where(language_de: true) }

  enum state: { rejected: 0, waiting_list: 1, application_selected: 2, cancelled: 3 }

  def at_least_select_one_language
    unless language_de? || language_en?
      errors.add(:language, "Please select at least one language.")
    end
  end

  def too_late_to_confirm?(date)
    return false unless selected_on
    date - selected_on > event.confirmation_deadline
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << [
        "Status",
        "Confirmed",
        "Name",
        "E-mail",
        "English",
        "German",
        "Attended before",
        "Rejected before",
        "Level",
        "Operating system",
        "Needs computer",
        "Date of application",
        "Comments"
      ]
      all.each do |application|
        csv << [
          Application.human_attribute_name("state.#{application.state}"),
          I18n.t("csv_display.#{application.attendance_confirmed}"),
          application.name,
          application.email,
          I18n.t("csv_display.#{application.language_en}"),
          I18n.t("csv_display.#{application.language_de}"),
          I18n.t("csv_display.#{application.attended_before}"),
          I18n.t("csv_display.#{application.rejected_before}"),
          application.level,
          application.os,
          I18n.t("csv_display.#{application.needs_computer}"),
          application.created_at,
          application.comments
        ]
      end
    end
  end
end

app/controllers/admin/applications_controller.rb
class Admin::ApplicationsController < ApplicationController
  layout "admin"

  before_action :require_admin
  before_action :find_event

  def index
    @applications = @event.applications.order(params[:order] || "created_at desc")
    respond_to do |format|
      format.html
      format.csv { send_data @applications.to_csv }
    end
  end

  def update_statuses
    selected_ids = params[:selected_ids] || [-1]
    confirmed_ids = params[:confirmed_ids] || [-1]
    # This code might cause performance problems. If application too slow, it needs refactoring.
    params[:state].each do |application_id, state|
      application = Application.find(application_id)
      application.state = state
      application.save!
    end

    @event.applications.update_all(["attendance_confirmed = (id IN (?))", confirmed_ids])

    redirect_to admin_event_applications_path(@event), notice: "Cool! Changes saved."
  end

private

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
  helper_method :current_time

  # We want the periods to start and end at midnight in Berlin, not UTC.
  # A possible improvement could be to configure a time zone for each event, instead of hardcoding it to Berlin.
  def current_time
    Time.now.in_time_zone("Berlin").to_date
  end

  private

  def require_admin
    require_login
    if current_user && !current_user.admin
      redirect_to root_path
    end
  end

  def require_coach
    unless current_user && current_user.coach
      store_location
      flash[:notice] = "You need to be signed in as coach"
      redirect_to coaches_sign_in_path
    end
  end

  def require_signed_out
    redirect_to logged_in_path if current_user
  end
end

app/controllers/applications_controller.rb
require 'securerandom'

class ApplicationsController < ApplicationController
  before_action :find_event

  def new
    if @event.application_start > current_time
      render :too_early
    elsif @event.application_end < current_time
      render :too_late
    else
      @application = Application.new
    end
  end

  def create
    @application = @event.applications.build(params.require(:application).permit(:name,
      :email, :language_de, :language_en, :attended_before, :rejected_before, :level,
      :comments, :referred_by, :os, :needs_computer, :read_coc, :female))

    @application.random_id = SecureRandom.hex(12)
    @application.sequence_number = @event.applications.count + 1

    if @application.save
      UserMailer.application_mail(@application).deliver_later
    else
      render :new
    end
  end

  def confirm
    @application = @event.applications.application_selected.find_by!(random_id: params[:application_id])
    if @application.too_late_to_confirm?(current_time)
      render :confirmed_too_late
    else
      if @application.update_attributes(attendance_confirmed: true)
        render :confirm
      else
        render :error
      end
    end
  end

  def cancel
    @application = @event.applications.application_selected.find_by!(random_id: params[:application_id])
    if @application.update_attributes(state: "cancelled", attendance_confirmed: false)
      render :cancel
    else
      render :error
    end
  end

private

  def find_event
    @event = Event.find(params[:event_id])
  end
end

app/helpers/admin/applications_helper.rb
module Admin::ApplicationsHelper

  def order(field)
    if params[:order] == field
      "#{field} desc"
    else
      field
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def inside_layout(layout = "application", &block)
    render inline: capture(&block), layout: "layouts/#{layout}"
  end
  
end

app/helpers/applications_helper.rb
module ApplicationsHelper

  def error_message(object, field)
    object.errors[field].map do |error|
      "<p class=\"error_message\"> #{error} </p>"
    end.join.html_safe
  end

  def application_states_for_select
    Application.states.map do |key, _|
      [Application.human_attribute_name("state.#{key}"), key]
    end
  end
end

app/views/admin/applications/index.html.erb
<p><%= button_to("Download table as csv", {format: "csv"}, {method: :get}) %></p>

<% if @event.selection_complete %>
  <h3>The selection is completed and confirmation e-mails have been sent. If you select additional applicants, please click the "Send e-mails" button to send them the e-mail.</h3>
  <p><%= button_to "Send e-mails", admin_event_send_emails_path(@event), method: :put, data: { confirm: "Are you sure? This will send e-mails to the selected applicants." } %></p>
<% else %>
  <p><%= button_to 'Selection complete', admin_event_complete_path(@event), method: :put, data: { confirm: "Are you sure? This will send e-mails to the selected applicants." } %></p>
<% end %>

<p>Total: <%= pluralize(@applications.size, "application") %> |
Selected: <%= pluralize(@applications.application_selected.size, "application") %> |
Waiting list: <%= pluralize(@applications.waiting_list.size, "application") %> |
Confirmed: <%= pluralize(@applications.application_selected.confirmed.size, "application") %> |
Cancelled: <%= pluralize(@applications.cancelled.size, "application") %> |
E-mail pending: <%= pluralize(@applications.application_selected.not_marked_as_selected.size, "application") %></p>

<%= form_tag({ action: :update_statuses }, method: :put) do %>
<table>
  <thead>
    <tr>
      <th><%= link_to("No.", order: order("sequence_number"), class: "table-header-link") %></th>
      <th><%= link_to("Status", order: order("state"), class: "table-header-link") %></th>
      <th><%= link_to("Confirmed", order: order("attendance_confirmed"), class: "table-header-link") %></th>
      <th><%= link_to("Name", order: order("upper(name)"), class: "table-header-link") %></th>
      <th><%= link_to("Email", order: order("upper(email)"), class: "table-header-link") %></th>
      <th><div class="tooltip"><span class="tooltiptext">English</span><%= link_to("🇬🇧", order: order("language_en")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">German</span><%= link_to("🇩🇪", order: order("language_de")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">Attended before</span><%= link_to("👍", order: order("attended_before")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">Rejected before</span><%= link_to("👎", order: order("rejected_before")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">Level</span><%= link_to("🎓", order: order("level")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">Operating System</span><%= link_to("🖥", order: order("os")) %></div></th>
      <th><div class="tooltip"><span class="tooltiptext">Needs computer</span><%= link_to("💻", order: order("needs_computer")) %></div></th>
      <th><%= link_to("Date", order: order("created_at"), class: "table-header-link") %></th>
      <th><%= link_to("Comments", order: order("comments"), class: "table-header-link") %></th>
    </tr>
  </thead>
  <tbody>
    <% @applications.each do |application| %>
    <tr>
      <td><%= application.sequence_number %>.</td>
      <td class="<%= application.state %>"><%= select_tag "state[#{application.id}]", options_for_select(application_states_for_select, application.state) %></td>
      <td>
        <div style="text-align:center"><%= check_box_tag 'confirmed_ids[]', application.id, application.attendance_confirmed, id: "confirm_applicant_#{application.id}" %></div>
        <div style="text-align:left"><%= application.application_selected? && application.too_late_to_confirm?(current_time) && !application.attendance_confirmed? ? "<div class='tooltip'><span class='tooltiptext'>Not confirmed in time</span>⏰</div>".html_safe : "" %></div>
      </td>
      <td><%= application.name %></td>
      <td><%= application.email %></td>
      <td class="center"><% if application.language_en %> ✅ <% end %></td>
      <td class="center"><% if application.language_de %> ✅ <% end %></td>
      <td class="center"><% if application.attended_before %> ✅ <% end %></td>
      <td class="center"><% if application.rejected_before %> ✅ <% end %></td>
      <td class="center"><%= application.level %></td>
      <td><%= application.os %></td>
      <td class="center"><% if application.needs_computer %> ✅ <% end %></td>
      <td><%= l application.created_at, format: :date %></td>
      <td class="shorten-long-text"><%= application.comments %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p><%= submit_tag "Save" %></p>
<% end %>